/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pkg1;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import java.text.DecimalFormat;
/**
 *
 * @author john
 */
public class ScreenMain extends javax.swing.JFrame {

    /**
     * Creates new form ScreenMain
     */
    private double ticketPrice = 0.0;
    private double enteredAmount = 0.0;
    DecimalFormat f = new DecimalFormat("##.00");
    public void resetFields()
    {
        ticketPrice = 0.0;
        enteredAmount = 0.0;
    }
    public ScreenMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("US iGO 04");
        setPreferredSize(new java.awt.Dimension(420, 500));

        jInternalFrame1.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(204, 204, 255)));
        jInternalFrame1.setTitle("Purchase Tickets with Cash");
        jInternalFrame1.setFocusTraversalPolicyProvider(true);
        try {
            jInternalFrame1.setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        jInternalFrame1.setVisible(true);
        jInternalFrame1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showCashScreen(evt);
            }
        });

        jButton1.setText("1 trip $3.15");
        jButton1.setActionCommand("1 trip $3.15");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                oneTripClick(evt);
            }
        });

        jButton2.setText("2 trips $6.50");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                twoTripsClick(evt);
            }
        });

        jButton3.setLabel("One Day $10");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                oneDayClick(evt);
            }
        });

        jButton4.setLabel("Weekly $25");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                weeklyClicked(evt);
            }
        });

        jButton5.setLabel("Unlimited Weekend $17");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                weekendClicked(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addContainerGap(166, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showCashScreen(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showCashScreen
        // TODO add your handling code here:

    }//GEN-LAST:event_showCashScreen

    private void weekendClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_weekendClicked
        // TODO add your handling code here:
        ticketPrice = 17.00;
        
        javax.swing.JTextField field  = new javax.swing.JTextField();
        field.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if (!((c >= '0') && (c <= '9') ||
                    (c == KeyEvent.VK_BACK_SPACE) ||
                    (c == KeyEvent.VK_PERIOD) ||
                    (c == KeyEvent.VK_DELETE))) {
                        getToolkit().beep();
                        e.consume();
                    }
            }
        });
        
//enteredAmount = Float.valueOf(JOptionPane.showInputDialog(jInternalFrame1,"Enter the amount of cash", null));
        
        JOptionPane.showMessageDialog(rootPane, field, "Enter Cash", 3);
        enteredAmount = Double.valueOf((String.valueOf(field.getText())));
        
        if(enteredAmount > ticketPrice){
            double diff = enteredAmount-ticketPrice;
            Object msg = (Object)("Thank you! Please collect your ticket. \nReturning change : $"+(f.format(diff)));
            JOptionPane.showConfirmDialog(rootPane, msg, "Info", 2, 1);
        }else if(enteredAmount < ticketPrice){
            Object msg = (Object)("Sorry.The amount you entered is not enough.");
            JOptionPane.showConfirmDialog(rootPane, msg, "Info", 2, 0);
        }else{
            Object msg = (Object)("Thank you! Please collect your ticket");
            JOptionPane.showConfirmDialog(rootPane, msg, "Info", 2, 1);
        }

    }//GEN-LAST:event_weekendClicked

    private void weeklyClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_weeklyClicked
        // TODO add your handling code here:
        ticketPrice = 25.00;
        
        javax.swing.JTextField field  = new javax.swing.JTextField();
        field.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if (!((c >= '0') && (c <= '9') ||
                    (c == KeyEvent.VK_BACK_SPACE) ||
                    (c == KeyEvent.VK_PERIOD) ||
                    (c == KeyEvent.VK_DELETE))) {
                        getToolkit().beep();
                        e.consume();
                    }
            }
        });
        
//enteredAmount = Float.valueOf(JOptionPane.showInputDialog(jInternalFrame1,"Enter the amount of cash", null));
        
        JOptionPane.showMessageDialog(rootPane, field, "Enter Cash", 3);
        enteredAmount = Double.valueOf((String.valueOf(field.getText())));
        
        if(enteredAmount > ticketPrice){
            double diff = enteredAmount-ticketPrice;
            Object msg = (Object)("Thank you! Please collect your ticket. \nReturning change : $"+(f.format(diff)));
            JOptionPane.showConfirmDialog(rootPane, msg, "Info", 2, 1);
        }else if(enteredAmount < ticketPrice){
            Object msg = (Object)("Sorry.The amount you entered is not enough.");
            JOptionPane.showConfirmDialog(rootPane, msg, "Info", 2, 0);
        }else{
            Object msg = (Object)("Thank you! Please collect your ticket");
            JOptionPane.showConfirmDialog(rootPane, msg, "Info", 2, 1);
        }
    }//GEN-LAST:event_weeklyClicked

    private void oneDayClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oneDayClick
        // TODO add your handling code here:
        ticketPrice = 10.00;
        
        
        javax.swing.JTextField field  = new javax.swing.JTextField();
        field.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if (!((c >= '0') && (c <= '9') ||
                    (c == KeyEvent.VK_BACK_SPACE) ||
                    (c == KeyEvent.VK_PERIOD) ||
                    (c == KeyEvent.VK_DELETE))) {
                        getToolkit().beep();
                        e.consume();
                    }
            }
        });
        
//enteredAmount = Float.valueOf(JOptionPane.showInputDialog(jInternalFrame1,"Enter the amount of cash", null));
        
        JOptionPane.showMessageDialog(rootPane, field, "Enter Cash", 3);
        enteredAmount = Double.valueOf((String.valueOf(field.getText())));
        
        if(enteredAmount > ticketPrice){
            double diff = enteredAmount-ticketPrice;
            Object msg = (Object)("Thank you! Please collect your ticket. \nReturning change : $"+(f.format(diff)));
            JOptionPane.showConfirmDialog(rootPane, msg, "Info", 2, 1);
        }else if(enteredAmount < ticketPrice){
            Object msg = (Object)("Sorry.The amount you entered is not enough.");
            JOptionPane.showConfirmDialog(rootPane, msg, "Info", 2, 0);
        }else{
            Object msg = (Object)("Thank you! Please collect your ticket");
            JOptionPane.showConfirmDialog(rootPane, msg, "Info", 2, 1);
        }
    }//GEN-LAST:event_oneDayClick

    private void twoTripsClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_twoTripsClick
        // TODO add your handling code here:
        ticketPrice = 6.50;
        
        javax.swing.JTextField field  = new javax.swing.JTextField();
        field.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if (!((c >= '0') && (c <= '9') ||
                    (c == KeyEvent.VK_BACK_SPACE) ||
                    (c == KeyEvent.VK_PERIOD) ||
                    (c == KeyEvent.VK_DELETE))) {
                        getToolkit().beep();
                        e.consume();
                    }
            }
        });
        
//enteredAmount = Float.valueOf(JOptionPane.showInputDialog(jInternalFrame1,"Enter the amount of cash", null));
        
        JOptionPane.showMessageDialog(rootPane, field, "Enter Cash", 3);
        enteredAmount = Double.valueOf((String.valueOf(field.getText())));
        
        if(enteredAmount > ticketPrice){
            double diff = enteredAmount-ticketPrice;
            Object msg = (Object)("Thank you! Please collect your ticket. \nReturning change : $"+(f.format(diff)));
            JOptionPane.showConfirmDialog(rootPane, msg, "Info", 2, 1);
        }else if(enteredAmount < ticketPrice){
            Object msg = (Object)("Sorry.The amount you entered is not enough.");
            JOptionPane.showConfirmDialog(rootPane, msg, "Info", 2, 0);
        }else{
            Object msg = (Object)("Thank you! Please collect your ticket");
            JOptionPane.showConfirmDialog(rootPane, msg, "Info", 2, 1);
        }
    }//GEN-LAST:event_twoTripsClick

    private void oneTripClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oneTripClick
        // TODO add your handling code here:
        ticketPrice = 3.15;
        
        javax.swing.JTextField field  = new javax.swing.JTextField();
        field.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if (!((c >= '0') && (c <= '9') ||
                    (c == KeyEvent.VK_BACK_SPACE) ||
                    (c == KeyEvent.VK_PERIOD) ||
                    (c == KeyEvent.VK_DELETE))) {
                        getToolkit().beep();
                        e.consume();
                    }
            }
        });
        
//enteredAmount = Float.valueOf(JOptionPane.showInputDialog(jInternalFrame1,"Enter the amount of cash", null));
        
        JOptionPane.showMessageDialog(rootPane, field, "Enter Cash", 3);
        enteredAmount = Double.valueOf((String.valueOf(field.getText())));
        
        if(enteredAmount > ticketPrice){
            double diff = enteredAmount-ticketPrice;
            Object msg = (Object)("Thank you! Please collect your ticket. \nReturning change : $"+(f.format(diff)));
            JOptionPane.showConfirmDialog(rootPane, msg, "Info", 2, 1);
        }else if(enteredAmount < ticketPrice){
            Object msg = (Object)("Sorry.The amount you entered is not enough.");
            JOptionPane.showConfirmDialog(rootPane, msg, "Info", 2, 0);
        }else{
            Object msg = (Object)("Thank you! Please collect your ticket");
            JOptionPane.showConfirmDialog(rootPane, msg, "Info", 2, 1);
        }
    }//GEN-LAST:event_oneTripClick

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScreenMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScreenMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScreenMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScreenMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScreenMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JInternalFrame jInternalFrame1;
    // End of variables declaration//GEN-END:variables
}
